Repository WasteLabs/gps_activity, pull requests merged in 2022-08, with the labels that each got.

#10 Setup pip package distribution based on poetry manager
  .github/workflows/ci-tests.yaml
  LICENSE.txt
  Makefile
  README.md
  gps_activity/metrics/nodes/precision.py
  gps_activity/metrics/nodes/recall.py
  poetry.lock
  pyproject.toml
  requirements-dev-win-base.txt
  requirements-dev-win-geo.txt
  requirements-dev-win.txt
  requirements-dev.txt
  setup.cfg
  setup.py
Labels: devops

#13 Setup continuous delivery pipeline to PyPI
  .github/workflows/publish.yaml
  pyproject.toml
Labels: devops

#14 Fix execution of builds and publish to `PyPi` under poetry env
  .github/workflows/publish.yaml
Labels: devops

#15 Fix publish action pipeline
  .github/workflows/publish.yaml
Labels: devops

#16 Add functionality left joining clusters and plan to gps & activate pytest coverage report
  gps_activity/models.py
  setup.cfg
  tests/test_models.py
Labels: enhancement, devops

#17 Cover by documentation main modules
  README.md
  docs/extraction/Classification.png
  docs/extraction/Clustering.png
  docs/extraction/Fragmentation.png
  docs/extraction/README.md
  docs/gps_activity/extraction/available_models/README.md
  docs/gps_activity/extraction/available_models/VHFDBSCAN/README.md
  docs/linker/README.md
Labels: documentation

#18 Fix bug when `predict()` is called directly on fdbscan clustering instance
  gps_activity/extraction/nodes/fdbscan.py
Labels: bug

#19 Setup input `dataframe` copy for `AbstractPredictor` instances
  gps_activity/abstract.py
  gps_activity/extraction/nodes/__init__.py
  gps_activity/extraction/nodes/fdbscan.py
  gps_activity/extraction/nodes/stcm.py
  gps_activity/extraction/nodes/velocity_fragmentator.py
  tests/extraction/nodes/test_stcm.py
Labels: bug

#22 Git-flow merge of develop to main
  gps_activity/abstract.py
  gps_activity/extraction/nodes/__init__.py
  gps_activity/extraction/nodes/fdbscan.py
  gps_activity/extraction/nodes/stcm.py
  gps_activity/extraction/nodes/velocity_fragmentator.py
  tests/extraction/nodes/test_stcm.py
Labels: maintenance
